import { existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { execFileSync, execSync } from 'child_process';
import { projectRoot, stats, RED, GREEN, NC } from './utils.js';

function pass(message) {
  console.log(`  ${GREEN}✓${NC} ${message}`);
  stats.pass++;
}

function fail(message) {
  console.error(`  ${RED}✗${NC} ${message}`);
  stats.fail++;
}

function gitLsFiles() {
  return execFileSync('git', ['ls-files'], { cwd: projectRoot, encoding: 'utf8' })
    .split(/\r?\n/)
    .filter(Boolean)
    .map((file) => file.replace(/\\/g, '/'));
}

function readTracked(file) {
  return readFileSync(join(projectRoot, file), 'utf8');
}

function isTextFile(file) {
  return /\.(md|txt|json|jsonl|yaml|yml|js|ts|tsx|jsx|sh|ps1|html|css|svg|xml|toml|ini|config|gitignore|npmignore|gitattributes|editorconfig)$/i.test(file) ||
    !file.includes('.');
}

function isAllowedSyntheticSecretFile(file) {
  const normalized = file.replace(/\\/g, '/');
  return normalized.startsWith('tests/') ||
    normalized.startsWith('scripts/verify/') ||
    normalized === 'scripts/verify.sh' ||
    normalized.startsWith('src/gateway/') ||
    normalized.startsWith('.ai/models/') ||
    normalized.startsWith('docs/gateway-') ||
    normalized === 'docs/v4.2-release-readiness.md';
}

function checkNoTrackedForbiddenPaths(files) {
  const forbiddenPatterns = [
    /^\.local-ai\//,
    /^\.ai-private\//,
    /^\.dev-workspace\//,
    /^\.codex-local\//,
    /^\.antigravity-local\//,
    /^\.codex\//,
    /^\.claude\//,
    /^\.cursor\//,
    /^\.gemini\//,
    /^\.antigravity\//,
    /(^|\/)private-prompts\//,
    /(^|\/)private-context\//,
    /(^|\/)scratchpad\//,
    /(^|\/)work-notes\//,
    /(^|\/)implementation-notes\//,
    /(^|\/)session-logs\/(?!README\.md$)/,
    /(^|\/)\.env($|\.)/,
    /(^|\/)\.npmrc$/,
    /(^|\/)\.ai\/registry-signing-key$/,
    /(^|\/)\.gateway-(data|logs|traces|metrics)\//,
    /(^|\/).*\.pid$/,
    /(^|\/)coverage\//,
    /^docs\/\.vitepress\/(dist|cache|\.temp)\//,
    /^\.release\//,
    /(^|\/)(chat-export|conversation-export|codex-transcript|agent-transcript|pasted-chat)/i,
    /(^|\/)Pasted (text|markdown)/i
  ];

  const offenders = files.filter((file) => forbiddenPatterns.some((pattern) => pattern.test(file)));
  if (offenders.length === 0) pass('Forbidden private workflow paths are not tracked');
  else fail(`Forbidden private workflow paths are tracked: ${offenders.join(', ')}`);
}

function checkRootContractsArePublicTemplates(files) {
  const rootContracts = ['AGENTS.md', 'MEMORY.md', 'TASKS.md', 'RUNBOOK.md'];
  const missing = rootContracts.filter((file) => !files.includes(file));
  if (missing.length === 0) pass('Root workspace contracts remain present as public templates');
  else fail(`Root workspace contracts missing: ${missing.join(', ')}`);

  const forbidden = /(Sprint [A-H]\b|v4\.2 Sprint|npm latest|manually published|GitHub release|Deploy Docs|CI Verification|READY FOR|FULLY RELEASED|Current state:|Preflight State|Final Report|End with exactly)/i;
  const offenders = rootContracts.filter((file) => files.includes(file) && forbidden.test(readTracked(file)));
  if (offenders.length === 0) pass('Root workspace contracts do not contain private release workflow state');
  else fail(`Root workspace contracts contain private release workflow state: ${offenders.join(', ')}`);
}

function checkIgnoreRules() {
  const samples = [
    '.local-ai/test.md',
    '.ai-private/test.md',
    'private-prompts/example.md',
    'session-logs/example.md',
    '.gateway-logs/runtime.log',
    'codex-transcript-001.md'
  ];
  const notIgnored = [];
  for (const sample of samples) {
    try {
      execFileSync('git', ['check-ignore', '-q', sample], { cwd: projectRoot, stdio: 'pipe' });
    } catch {
      notIgnored.push(sample);
    }
  }

  if (notIgnored.length === 0) pass('Private workspace and transcript patterns are ignored');
  else fail(`Private workspace patterns are not ignored: ${notIgnored.join(', ')}`);
}

function checkWorkflowTellPhrases(files) {
  const phrasePatterns = [
    /generated by (ai|codex|chatgpt)/i,
    /written by (ai|codex|chatgpt)/i,
    /vibe[- ]?coded/i,
    /context automatically compacted/i,
    /^you are working on\s+[`"A-Z:]/im,
    /end with exactly/i,
    /stop and report/i,
    /chain of thought/i,
    /raw chat transcript/i,
    /agent transcript/i
  ];
  const allowedFiles = new Set([
    'scripts/verify/repository-hygiene.js'
  ]);
  const offenders = [];
  for (const file of files) {
    if (allowedFiles.has(file) || !isTextFile(file)) continue;
    const content = readTracked(file);
    if (phrasePatterns.some((pattern) => pattern.test(content))) offenders.push(file);
  }
  if (offenders.length === 0) pass('Tracked text files are free of private AI workflow tell phrases');
  else fail(`Private AI workflow tell phrases found in: ${offenders.join(', ')}`);
}

function checkMachinePaths(files) {
  const pathPattern = /([A-Z]:\\Users\\[^\\\s]+|\/home\/[^/\s]+|\/Users\/[^/\s]+)/;
  const offenders = [];
  for (const file of files) {
    if (!isTextFile(file) || isAllowedSyntheticSecretFile(file)) continue;
    if (pathPattern.test(readTracked(file))) offenders.push(file);
  }
  if (offenders.length === 0) pass('No public tracked text contains machine-specific user paths');
  else fail(`Machine-specific paths found in public tracked files: ${offenders.join(', ')}`);
}

function checkSecretPatterns(files) {
  const secretPattern = /(sk-[a-z0-9_-]{8,}|AIza[a-z0-9_-]{8,}|bearer +[a-z0-9._-]{8,}|password\s*[:=]\s*["']?[^"'\s]+|authorization\s*[:=]\s*["']?bearer\s+[a-z0-9._-]{8,})/i;
  const offenders = [];
  for (const file of files) {
    if (!isTextFile(file) || isAllowedSyntheticSecretFile(file)) continue;
    if (secretPattern.test(readTracked(file))) offenders.push(file);
  }
  if (offenders.length === 0) pass('No public tracked text contains credential-looking values');
  else fail(`Credential-looking values found in public tracked files: ${offenders.join(', ')}`);
}

function checkNpmPackHygiene() {
  const output = execSync('npm pack --dry-run --json', {
    cwd: projectRoot,
    encoding: 'utf8',
    env: { ...process.env, MMDO_ALLOW_PUBLISH: 'true' }
  });
  const pack = JSON.parse(output)[0];
  const files = pack.files.map((entry) => String(entry.path || '').replace(/\\/g, '/'));
  const forbidden = files.filter((file) =>
    file.includes('.npmrc') ||
    file.includes('.env') ||
    file.includes('node_modules') ||
    file.includes('coverage/') ||
    file.includes('docs/.vitepress/dist/') ||
    file.includes('.release/') ||
    file.includes('.local-ai/') ||
    file.includes('.ai-private/') ||
    /(^|\/)session-logs\/(?!README\.md$)/.test(file) ||
    /(^|\/)(chat-export|conversation-export|codex-transcript|agent-transcript|pasted-chat)/i.test(file) ||
    file.endsWith('.pid') ||
    file.includes('.gateway-logs/') ||
    file.includes('.gateway-traces/') ||
    file.includes('.gateway-metrics/')
  );

  if (forbidden.length === 0) pass('npm package excludes private workflow and runtime-state files');
  else fail(`npm package includes private workflow or runtime-state files: ${forbidden.join(', ')}`);
}

export function checkRepositoryHygiene() {
  console.log('\nPublic Repository Hygiene Verification:');
  const files = gitLsFiles();
  checkNoTrackedForbiddenPaths(files);
  checkRootContractsArePublicTemplates(files);
  checkIgnoreRules();
  checkWorkflowTellPhrases(files);
  checkMachinePaths(files);
  checkSecretPatterns(files);
  checkNpmPackHygiene();
}
