import { version } from '../core/globals.js';

export function showHelp() {
  console.log(`\n🧠 \x1b[36mmultimodel-dev-os CLI v${version}\x1b[0m`);
  console.log('====================================');
  console.log('Usage: node bin/multimodel-dev-os.js <command> [options]\n');
  console.log('Commands:');
  console.log('  init              Initialize a project with configs and adapters');
  console.log('  scan              Scan project structure and framework signals');
  console.log('  status            Show compact dashboard summarizing repository intelligence state');
  console.log('  dashboard         Launch the interactive terminal command center (alias: ui)');
  console.log('  memory <subcmd>   Manage hash-compressed codebase memory (subcmd: build, refresh, diff)');
  console.log('  feedback <subcmd> Manage developer feedback loops (subcmd: add, list, summarize)');
  console.log('  improve <subcmd>  Manage codebase self-improvement proposals (subcmd: propose, review, status, validate, diff, apply, log)');
  console.log('  workflow <subcmd> Orchestrate read-only development workflow pipelines (subcmd: list, show, plan, run)');
  console.log('  handoff <subcmd>  Compile or print token-compressed agent session summaries (subcmd: build, show)');
  console.log('  onboard <subcmd>  Safely integrate MultiModel Dev OS into existing repo (subcmd: analyze, recommend, plan, apply, status)');
  console.log('  adapter <subcmd>  Manage and sync rule/settings files for IDE adapters (subcmd: status, diff, sync)');
  console.log('  plugin <subcmd>   Manage declarative plugins (subcmd: list, show, validate, install, status)');
  console.log('  catalog <subcmd>  Manage Workflow Marketplace & Plugin Catalog (subcmd: list, search, show, categories, recommend, install, status)');
  console.log('  registry <subcmd> Manage trusted remote catalog registries (subcmd: list, add, remove, sync, status, verify, show, cache)');
  console.log('  verify            Validate structural integrity of an existing project');
  console.log('  templates         List all built-in template profiles with details');
  console.log('  list-templates    Alias for templates command');
  console.log('  show-template <t> Inspect detailed stack specifications of template <t>');
  console.log('  doctor            Advisory checkup of project compatibility loops and ignored folders');
  console.log('  validate          Strict validation checks to verify directory schema compliance');
  console.log('  validate-template Validate registry keys and source folder files for template');
  console.log('  validate-adapter  Validate registry keys and source assets for IDE adapter');
  console.log('  validate-skill    Verify custom skill conforms to core prompt structure');
  console.log('  models            List registered model aliases in the capabilities registry');
  console.log('  show-model <m>    View specifications of model <m> in registry');
  console.log('  providers         List configured AI provider API endpoints');
  console.log('  route-model <tsk> Suggest optimal model mapping for task <tsk>');
  console.log('  adapters          List IDE and terminal tool adapters');
  console.log('  show-adapter <a>  Inspect config specifications of adapter <a>');
  console.log('  skills            List active skills custom prompts in target workspace');
  console.log('  show-skill <s>    View prompt contents of target workspace skill <s>\n');
  console.log('Options:');
  console.log('  -t, --target <path>     Target folder destination (default: current working directory)');
  console.log('  --type <type>           Feedback classification (correction, preference, bug, etc.)');
  console.log('  --tags <list>           Comma-separated descriptor tags for feedback');
  console.log('  --files <list>          Comma-separated target files for feedback');
  console.log('  --category <name>       Filter catalog plugins list by category');
  console.log('  --source <src>          Catalog source filter: bundled, local, or remote:<name>');
  console.log('  --all-sources           Include all enabled catalog sources in listings');
  console.log('  --title <text>          Specifies title for codebase improvement proposal');
  console.log('  --approved              Explicitly approve and execute proposal/onboarding/adapter sync writes');
  console.log('  --template <name>       Template profile: nextjs-saas, expo-react-native-android, etc.');
  console.log('  -a, --adapter <name>    Inject specific adapter: cursor, claude, vscode, gemini, etc.');
  console.log('  --caveman               Use minimal-token templates (~79% fewer tokens)');
  console.log('  --tokens                Run a deeper token-sink size analysis during doctor checkup');
  console.log('  --intelligence          Run diagnostic checkup of repository intelligence config');
  console.log('  --onboarding            Run diagnostic checkup of repository onboarding setup');
  console.log('  --json                  Output raw JSON data for listing commands (models, adapters, templates)');
  console.log('  --threshold <val>       Set custom size threshold for doctor tokens checks (e.g. 50KB)');
  console.log('  --registry <path>       Override default registry (for templates/adapters list or check)');
  console.log('  -d, --dry-run           Preview planned file actions without modifying the filesystem');
  console.log('  -f, --force             Overwrite existing files without prompting\n');
}
